import createFetchClient, { Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api/v1"; // generated by openapi-typescript

const apiKey = "9513d312-f377-4e08-b38a-f586570f984b";

const authMidleware: Middleware = {
  async onRequest( {request} ) {
    request.headers.set( "X-API-KEY", `${apiKey}` );
  }
};
const fetchClient = createFetchClient<paths>( {
  baseUrl : "http://localhost:3000/api",
} );
fetchClient.use( authMidleware );

const $api = createClient( fetchClient );


export {$api};
